name: Self-hosted runner (push-caller)

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"
      - "templates/**"
      - "utils/**"

jobs:
  run_push_ci:
    name: Run Push CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Checkout to branch push-ci
        run: |
          git fetch origin
          git checkout push-ci
          git pull origin main
          git push
